### PR TITLE
Add RowRelationTest

### PR DESCRIPTION
**Pull request by srfc**
## Proposed Changes

  - Add test for RowRelation

## Related

  - #20 
  - merge PR #30 first
  - depends on #26

### CODE REVIEW

**Comment by srfc** [comment]
With regard to the failed tests here to issues are apparent:
- we should add success feedback in the form of `Try` to `insertAll` as well
- `whereAll` queries fail if they encounter missing values in one of their respective columns
- `where` cannot match on an empty field for a column, even if the matching function always returns true

I think the latter two, are bugs that should be fixed. What do you think of `insertAll` returning a `Try` analogously to `insert`?

**Comment by CodeLionX** [comment]
Can you already work on the mentioned issues for `when`?
Otherwise, I would suggest creating issues for that, so we can merge this PR anyway.

Regarding `insertAll`, I'm totally fine with also changing its return type to `Try[Seq[Record]]`, but then we should make clear its semantics. I would prefer it to be an atomic operation (this will need some more logic, but should be possible).

**Comment by srfc** [comment]
W.r.t. the two bugs, i.e. `whereAll` queries failing on missing values and `where` not being able to match on an empty field I will need some time to fix.
I will create issues for all three cases and `ignore` the failing test cases so that we can merge.

**Comment by CodeLionX** [comment]
Please mark the test as `pending` instead of ignoring it.

Thanks for all the issues: #35, #36, #37, #34

**Pull request merged**
