### PR TITLE
Memory Experiments v2

### PR DESCRIPTION
**Pull request by CodeLionX**
## Proposed Changes

  - Add Memory Benchmark Code
  - Add Memory Benchmark Results

## Related

  - [old branch](https://github.com/CodeLionX/actordb/tree/feature/memory-experiments)

### CODE REVIEW

**Comment by CodeLionX** [comment]
### Analysis of Memory Overhead of `RowRelation`
Blog post talking about memory consumption of different scala/java collections by Haoyi (you should really know him, when writing scala :wink: ): http://www.lihaoyi.com/post/BenchmarkingScalaCollections.html
He writes:

> Small `Vector`s have 3-5x as much memory overhead as small `Array`s: a 1-element vector takes a 1/5th of a kilobyte of memory!
>
>For size 16 the overhead shrinks to ~30%, and for size 1,048,576 the overhead is down to about 5%. While the internal machinery means small `Vector`s use memory wastefully, for larger `Vector`s the overhead compared to a (boxed) `Array` [`scala.immutable.Array[java.lang.Object]`] is negligible.
>
> - Annotations by me in `[]`

[Table: Memory use of Arrays](http://www.lihaoyi.com/post/BenchmarkingScalaCollections.html#memory-use-of-arrays) shows the difference of array sizes when using various data types.

> The memory usage of the various unboxed Arrays of primitives is an order of magnitude less than that of the boxed Array[Object]. This makes sense, as a Array[Object] needs to store a 4-byte pointer to each entry, which itself is an object with a 16-byte object header [...].

1. we use a lot of small `Vector`s inside of `Relation`, because we have `Vector[Vector[Object]]` (n x m, n: #rows in relation, m: #cols in relation, usually we have n `Vector[Object]` with m < 16 :arrow_right: ~4n x overhead).
2. we use `Vector[Any]` == `Vector[java.lang.Object]`, which takes a 4 Byte pointer for each entry regardless of the real data type

:arrow_right: `Vector[Vector[Any]]` is in terms of memory a bad container
:arrow_right: `Vector[Any]` with size nm and custom indexing should be much much better (only reasonable slight overhead to `Array[Object]`), but needs a lot of thought for inserts and updates
:arrow_right: **`Array[Array[Any]]` could reduce memory overhead by a factor of 3-5**
:arrow_right: column-wise storage should be much better as type info could be used to store data in `Array` of `Array[<primitive type>]`s with m x n

**Comment by CodeLionX** [comment]
### Practical Analysis of Memory Overhead of `RowRelation`
Using medium dataset generated with default values of `generateData.sh`-script.

|  | Instances | Instance Size | Total Size | Retained Size |
|:-|:------------ | ----------------: | ------------: | -----------------: |
| `RowRelation` using `Vector[Vector[Any]]` | 4 808 | 40 | 192 320 | 114 578 447 |
| `RowRelation` using `Array[Array[Any]]` | 4 808 | 40 | 192 320 | 42 412 251 |

**Comment by srfc** [comment]
Big 👍 on your analysis and workflow description for measuring the retained sizes of only our `RowRelation` instances.

The improvement of using `Array[Array[Any]]` is substantial, but, as you've said in the first post, I think using a column-oriented store internally to be able to make use specific types of a column will improve memory usage even more. I think this is out of scope for the (very) immediate future/present, but I think this should be on our roadmap `Relation` and memory-wise.

Does using arrays instead of vectors remove any functionality that we rely on at the moment? I don't think so, but want to make sure since you rewrote the internal storage of `RowRelation`.

Thanks for looking into this and for the blog resource, bookmarked it already!

**Comment by CodeLionX** [comment]
The change from `Vector` to `Array` did not change the code inside our `Relation`s significantly as you can see in PR #115 :sunglasses: 

Should we create an issue regarding the change to column-oriented storage?

**Comment by CodeLionX** [comment]
I uploaded the heap dumps to [Drive (klick to view)](https://drive.google.com/drive/folders/10-kyenRfw0ALRxofYHXaWeVNsvARlW5X?usp=sharing). They can be viewed with VisualVM:

File > Load > (Select _Heap Dump_ as File type) > Select File > Open

It is very interesting; you can even see the individual overhead of Akka Actors of the different `Dactor`-types.

**Comment by CodeLionX** [comment]
merging without review as we already discussed the results and the approach multiple times

**Pull request merged**
